global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus scrapes itself
  # Add other jobs here to monitor your applications or infrastructure
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node_exporter:9100'] # Example for a node exporter
